apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deployment
  namespace: meetup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: registry.k3s/awsmeetup/service-1:202001221100
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
