apiVersion: v1
kind: Service
metadata:
  name: service-v1-service
  namespace: meetup
spec:
  type: LoadBalancer
  selector:
    app: service-v1
  ports:
  - nodePort: 30001
    port: 8000
    protocol: TCP
    targetPort: 8000
