apiVersion: v1
kind: Service

metadata:
  name: calc-service
  namespace: meetup

spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: calc-service

  ports:
    - name: http
      port: 8000
      protocol: TCP